### ISSUE TITLE
Can you please help me ?

### ISSUE THREAD

**Issue by YashKumarVerma** [unk1911/speech#2]
I am seriously in love with your work. Can you please help me in one thing ? I need to edit it in such a way that I shall pass only one variable into a single function. 

example

`function speak(text)`

`{`

`all condensed code`

`}`

_things like accent and pace and pitch will be pre-defined_

thanks in advance

**Comment by EdDT-Phi** [comment]
Probably too late, but if you pass in your text to his TTS function, that would do the trick, provided you predefine everything else

**Comment by YashKumarVerma** [comment]
I made it work! Thanks 👍
